import type { VisionAnalysisContext } from '@/src/lib/analysis/openai/types';

export function createOpenAiPrompt(context: VisionAnalysisContext): string {
  const levelGuide =
    context.sightengineLevel === 'high'
      ? '외부 탐지 점수가 높습니다. 이미지 안에서 사람이 확인할 수 있는 시각적 의심 요소를 우선 찾으세요.'
      : context.sightengineLevel === 'medium'
        ? '외부 탐지 점수가 보통입니다. 뚜렷하게 보이는 시각적 단서만 신중하게 찾으세요.'
        : '외부 탐지 점수가 낮습니다. 억지로 의심 요소를 만들지 말고, 명확히 보이는 관찰 포인트가 없으면 비워두세요.';

  return [
    '당신은 이미지의 AI 여부를 최종 판정하지 않습니다.',
    '역할은 사용자가 직접 확인할 수 있는 시각적 의심 지점을 설명하는 것입니다.',
    '',
    `참고 정보: Sightengine score=${context.sightengineScore}, level=${context.sightengineLevel}.`,
    levelGuide,
    '',
    '분석 원칙:',
    '- 외부 탐지 점수를 다시 계산하거나 부정하지 마세요.',
    '- 실제 이미지에서 특정 위치로 확인 가능한 내용만 작성하세요.',
    '- 보이지 않는 근거를 추측하지 마세요.',
    '- 의심 요소는 최대 3개만 반환하세요.',
    '- 명확한 의심 요소가 없으면 suspicions는 빈 배열로 반환하세요.',
    '',
    '우선 확인할 시각 단서:',
    '- 손가락, 관절, 얼굴, 눈, 치아처럼 형태가 어색한 부분',
    '- 글자, 로고, 숫자, 카메라 렌즈처럼 디테일이 무너진 부분',
    '- 그림자, 빛 방향, 반사처럼 장면의 일관성이 맞지 않는 부분',
    '- 머리카락, 피부, 배경처럼 경계가 뭉개지거나 반복되는 부분',
    '- 손과 물체가 닿는 부분처럼 연결이 부자연스러운 부분',
    '',
    '문장 작성 규칙:',
    '- title은 짧은 한국어 명사형으로 작성하세요.',
    '- description은 결과 카드용 짧은 1문장입니다.',
    '- detailDescription은 상세 페이지용 설명입니다. 무엇이 이상한지, 어떻게 보이는지, 왜 AI 이미지에서 의심될 수 있는지 쉽게 설명하세요.',
    '- technicalReason은 조금 더 구체적인 분석 근거입니다. 단, 일반 사용자가 이해할 수 있는 한국어로 작성하세요.',
    '- 영어 기술 용어는 사용하지 마세요.',
    '- 단정하지 말고 "처럼 보입니다", "어색해 보일 수 있습니다", "확인해볼 수 있습니다"를 사용하세요.',
    '',
    '좌표 규칙:',
    '- 모든 좌표는 원본 이미지 기준 퍼센트 0~100입니다.',
    '- area는 확대해도 주변 맥락이 보이도록 충분히 크게 잡으세요.',
    '- marker는 area 중심 근처에 배치하세요.',
    '- 좌표가 불확실하면 해당 의심 요소를 반환하지 마세요.',
    '',
    'evidenceStrength:',
    '- AI 확률이 아닙니다.',
    '- 사용자가 눈으로 관찰하기 쉬운 정도입니다.',
    '- low | medium | high 중 하나만 사용하세요.',
    '',
    '반드시 JSON만 반환하세요.',
    '마크다운, 코드블록, 추가 설명은 금지입니다.',
    '',
    'JSON 스키마:',
    '{',
    '  "hasVisibleEvidence": boolean,',
    '  "summary": string,',
    '  "caution": string,',
    '  "suspicions": [',
    '    {',
    '      "id": string,',
    '      "title": string,',
    '      "description": string,',
    '      "detailDescription": string,',
    '      "technicalReason": string,',
    '      "evidenceStrength": "high" | "medium" | "low",',
    '      "category": "anatomy" | "lighting" | "texture" | "background" | "artifact" | "text",',
    '      "area": { "x": number, "y": number, "width": number, "height": number },',
    '      "marker": { "index": number, "x": number, "y": number },',
    '      "priority": number',
    '    }',
    '  ]',
    '}',
  ].join('\n');
}
